name: Deploy EKS Cluster

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="bucket=my-terraform-state-bucket" \
          -backend-config="key=my-eks-cluster/terraform.tfstate" \
          -backend-config="region=us-east-1"

    - name: Plan Terraform changes
      run: |
        terraform plan \
          #-var="cluster_name=my-eks-cluster" \
          #-var="region=us-east-1"

    - name: Apply Terraform changes
      run: |
        terraform apply -auto-approve \
          #-var="cluster_name=my-eks-cluster" \
          #-var="region=us-east-1"
     
    - name: Wait for application to start
      run: sleep 300
    - name: destroy eks cluster
      run: terraform destroy -auto-approve
      
